# Generated by Django 3.2.4 on 2021-06-08 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '__first__'),
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Children_Tree',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name_node', models.CharField(max_length=150)),
                ('date_create', models.DateTimeField(blank=True, null=True)),
                ('children_folder', models.ManyToManyField(blank=True, related_name='children_tree', to='repository.Children_Tree')),
                ('files', models.ManyToManyField(blank=True, to='files.Files')),
                ('user_create', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
        migrations.CreateModel(
            name='Root_Tree',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name_branch', models.CharField(max_length=150)),
                ('date_create', models.DateTimeField(blank=True, null=True)),
                ('children_folder', models.ManyToManyField(blank=True, to='repository.Children_Tree')),
                ('files', models.ManyToManyField(blank=True, to='files.Files')),
                ('user_create', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=150)),
                ('date_create', models.DateTimeField(blank=True, null=True)),
                ('date_close', models.DateTimeField(blank=True, null=True)),
                ('type_project', models.BooleanField(default=True)),
                ('root_tree', models.ManyToManyField(blank=True, to='repository.Root_Tree')),
            ],
        ),
        migrations.CreateModel(
            name='List_Project_User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repository.project')),
                ('role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
    ]
